twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        timezone: Europe/Paris
    form_themes: ['bootstrap_4_layout.html.twig']