index:
    path: /
    controller: App\Controller\AccueilController::index
competition:
    path: /competition
    controller: App\Controller\ChampionnatController::index
equipe:
    path : /equipe/{id}
    controller: App\Controller\EquipeController::getUneEquipe
    requirements:
        id: '\d+'
equipes:
    path: /equipes
    controller: App\Controller\EquipeController::getEquipes
calendrier_equipe:
    path: /equipe/calendrier/{id}
    controller: App\Controller\EquipeController::getCalendrier
    requirements:
        id: '\d+'
calendrier_equipe_autre_saison:
    path: /equipe/calendrier/{id}/{nomSaison}
    controller: App\Controller\EquipeController::getCalendrier
    requirements:
        id: '\d+'
effectif_equipe:
    path: /equipe/effectif/{id}
    controller: App\Controller\EquipeController::getEffectif
    requirements:
        id: '\d+'
effectif_equipe_autre_saison:
    path: /equipe/effectif/{id}/{nomSaison}
    controller: App\Controller\EquipeController::getEffectif
    requirements:
        id: '\d+'
classement_competition:
    path: /competition/classement/
    controller: App\Controller\ChampionnatController::getClassement
calendrier_competition:
    path: /competition/calendrier
    controller: App\Controller\ChampionnatController::getCalendrier
classement_competition_autre_saison:
    path: /competition/classement/{nomSaison}
    controller: App\Controller\ChampionnatController::getClassement
calendrier_competition_autre_saison:
    path: /competition/calendrier/{nomSaison}
    controller: App\Controller\ChampionnatController::getCalendrier
joueurs:
    path: /joueurs
    controller: App\Controller\JoueurController::getParNom
search_joueur:
    path: /joueurs/searchJoueur/
    controller: App\Controller\JoueurController::displayList
consulter_joueur:
    path: joueurs/{id}
    controller: App\Controller\JoueurController::getJoueur
    requirements:
        id: '\d+'
search_by_equipe:
    path: /joueurs/JoueursEquipe/
    controller: App\Controller\JoueurController:getByEquipe
search_by_nationalite:
    path: /joueurs/JoueursNationalite
    controller: App\Controller\JoueurController:getNationalite
display_by_nationalite:
    path: /joueurs/Joueurs/{nationalite}
    controller: App\Controller\JoueurController:getByNationalite
journee:
    path: /competition/journee/{id}
    controller: App\Controller\ChampionnatController:getJournee
    requirements:
        id: '\d+'
articles:
    path: /competition/articles
    controller: App\Controller\ChampionnatController:getArticles    
article:
    path: /competition/article/{id}
    controller: App\Controller\ChampionnatController:getArticle
    requirements:
        id: '\d+'
equipe_article:
    path: /equipe/articles/{id}
    controller: App\Controller\EquipeController::getArticles
    requirements:
        id: '\d+'